var myLove="I love only JS";
console.log(myLove);
var firstName="Shivani";
console.log("First Name: ",firstName);
var lastName="Shinde";
console.log("Last Name: ",lastName);
var age=23;
console.log("Age: ",age);
var address="Hinjewadi, Pune";
console.log("Address: ",address);
var pinCode=410435;
console.log("Pincode: ",pinCode);
var gender="Female";
console.log("Gender : ",gender);
var isMarried="Yes";
console.log("isMarried:",isMarried);
