var n1=10;
var n2=20;
console.log("Before Swapping");
console.log("n1=",n1);
console.log("n2=",n2);
console.log("After Swapping");
var temp=n1;
n1=n2;
n2=temp;
console.log("n1=",n1);
console.log("n2=",n2);